<?php

$text = 'Bavaria ipsum dolor sit amet do legst di nieda Maderln, Spezi. Ned unbandig midanand vo de wea nia ausgähd, kummt nia hoam pfundig koa obacht i hob di narrisch gean om auf’n Gipfe koa. Resch sodala g’hupft wia gsprunga, mogsd a Bussal resch hob mim a bissal Almrausch Biakriagal baddscher. Wos des is hoid aso a bissal wos gehd ollaweil wo hi, an hallelujah sog i, luja i Steckerleis Trachtnhuat auf’d Schellnsau in da greana Au! Luja Enzian Trachtnhuat des is schee Bradwurschtsemmal o’ha Schaung kost nix Trachtnhuat. Klampfn schaugn fei, Enzian des is schee.
Almrausch Habedehre in da i moan oiwei am acht’n Tag schuf Gott des Bia heid anbandeln etza nix measi. Naa liberalitas Bavariae nimmds des a ganze Hoiwe sammawiedaguad muass, i hob di narrisch gean. Barfuaßat an Ramasuri Leonhardifahrt Brotzeit wo hi, Schbozal measi kumm geh Griasnoggalsubbm Lewakaas. Biawambn wea nia ausgähd, kummt nia hoam um Godds wujn Schdarmbeaga See Leonhardifahrt Wurscht da wiavui Buam, wia da Buachbinda Wanninger Zwedschgndadschi: Gfreit mi anbandeln sowos Greichats Biawambn Griasnoggalsubbm moand in da i hab an hogg ma uns zamm?
Watschnpladdla Baamwach gfreit mi jo mei is des schee, Schorsch kimmt. Wos hob Gamsbart Ewig und drei Dog des Gidarn moand baddscher Bradwurschtsemmal fensdaln heid gfoids ma sagrisch guad. A ganze damischa mi Oachkatzlschwoaf Namidog a ganze Hoiwe, Lewakaas aasgem sog i gscheid: Hoid ded fias wann griagd ma nacha wos z’dringa resch: Lewakaas Sepp wolpern, lem und lem lossn. Schnacksln Griasnoggalsubbm ded mechad Servas wiavui, dringma aweng! Oachkatzlschwoaf Broadwurschtbudn Xaver, Schmankal umma! Griasnoggalsubbm i Vergeltsgott kimmt des is a gmahde Wiesn pfundig, is Watschnpladdla Servas! Jodler wia Schaung kost nix, glacht do i hob di narrisch gean samma? Hogg di hera Landla Bussal Goaßmaß, heitzdog a? Gor kimmt des is hoid aso da Kini owe fias i hab an i hob di liab. Pfenningguat noch da Giasinga Heiwog ja, wo samma denn ded Schneid Diandldrahn barfuaßat, Foidweg:
Da Woibbadinga da, hog di hi wui! Des muas ma hoid kenna om auf’n Gipfe af Radi wuid. Umma ham mei Sauakraud. Reiwadatschi zwoa Biawambn Lewakaas auf gehds beim Schichtl Broadwurschtbudn, Kirwa! Heimatland singan a bissal wos gehd ollaweil ned Ohrwaschl Almrausch! Almrausch Mamalad sauba spernzaln schoo, umma heid a so a Schmarn. Ewig und drei Dog abfieseln eam Haferl Lewakaas auszutzeln hoam do greaßt eich nachad a ganze Almrausch. Damischa i moan oiwei Schbozal iabaroi zua?
Schüds nei aba von hogg di hera scheans Bradwurschtsemmal gscheckate, Buam Wurscht auf der Oim, da gibt’s koa Sünd. G’hupft wia gsprunga Greichats hoam oba. Pfundig no a Maß griasd eich midnand sog i Enzian Namidog unbandig hinter’m Berg san a no Leit gwiss, umma pfiad de! Xaver mei is ma Wuascht dei auf’d Schellnsau. Charivari Meidromml resch a fescha Bua, mechad Gidarn. Naa i waar soweid Almrausch, Weiznglasl. Is di Kneedl sei Schorsch pfundig obacht nia need luja ned:
Ognudelt Haferl Fingahaggln lem und lem lossn von moand vo de sog i. Aba a bissal gschmeidig des muas ma hoid kenna Xaver is auf der Oim, da gibt’s koa Sünd Schbozal noch da Giasinga Heiwog. Geh singan i ded und sei, a Hoiwe i sog ja nix, i red ja bloß vui Marei. Des muas ma hoid kenna an Landla midanand ozapfa jo leck mi wuid Kneedl. Middn des basd scho des is schee Schuabladdla Watschnpladdla da. Liberalitas Bavariae hinter’m Berg san a no Leit i moan oiwei a ganze Hoiwe Reiwadatschi Blosmusi gscheit hod Ledahosn Obazda: 
';

$textArray = explode(',', $text);

print_r($textArray);